raw_read_chunk_size = 1000
FROM = 'from'
TO = 'to'
USER_ID = 'user_id'
CATEGORIES = 'categories'
FRIENDS = 'friends'
FRIENDS_COUNT = 'friends_count'

restaurant_categories = [
    "Afghan",
    "African",
    "Senegalese",
    "South African",
    "American (New)",
    "American (Traditional)",
    "Arabian",
    "Argentine",
    "Armenian",
    "Asian Fusion",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Barbeque",
    "Basque",
    "Belgian",
    "Brasseries",
    "Brazilian",
    "Breakfast & Brunch",
    "Pancakes",
    "British",
    "Buffets",
    "Bulgarian",
    "Burgers",
    "Burmese",
    "Cafes",
    "Themed Cafes",
    "Cafeteria",
    "Cajun/Creole",
    "Cambodian",
    "Caribbean",
    "Dominican",
    "Haitian",
    "Puerto Rican",
    "Trinidadian",
    "Catalan",
    "Cheesesteaks",
    "Chicken Shop",
    "Chicken Wings",
    "Chinese",
    "Cantonese",
    "Dim Sum",
    "Hainan",
    "Shanghainese",
    "Szechuan",
    "Comfort Food",
    "Creperies",
    "Cuban",
    "Czech",
    "Delis",
    "Diners",
    "Dinner Theater",
    "Eritrean",
    "Ethiopian",
    "Fast Food",
    "Filipino",
    "Fish & Chips",
    "Fondue",
    "Food Court",
    "Food Stands",
    "French",
    "Mauritius",
    "Reunion",
    "Game Meat",
    "Gastropubs",
    "Georgian",
    "German",
    "Gluten-Free",
    "Greek",
    "Guamanian",
    "Halal",
    "Hawaiian",
    "Himalayan/Nepalese",
    "Honduran",
    "Hong Kong Style Cafe",
    "Hot Dogs",
    "Hot Pot",
    "Hungarian",
    "Iberian",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Calabrian",
    "Sardinian",
    "Sicilian",
    "Tuscan",
    "Japanese",
    "Conveyor Belt Sushi",
    "Izakaya",
    "Japanese Curry",
    "Ramen",
    "Teppanyaki",
    "Kebab",
    "Korean",
    "Kosher",
    "Laotian",
    "Latin American",
    "Colombian",
    "Salvadoran",
    "Venezuelan",
    "Live/Raw Food",
    "Malaysian",
    "Mediterranean",
    "Falafel",
    "Mexican",
    "Tacos",
    "Middle Eastern",
    "Egyptian",
    "Lebanese",
    "Modern European",
    "Mongolian",
    "Moroccan",
    "New Mexican Cuisine",
    "Nicaraguan",
    "Noodles",
    "Pakistani",
    "Pan Asia",
    "Persian/Iranian",
    "Peruvian",
    "Pizza",
    "Polish",
    "Polynesian",
    "Pop-Up Restaurants",
    "Portuguese",
    "Poutineries",
    "Russian",
    "Salad",
    "Sandwiches",
    "Scandinavian",
    "Scottish",
    "Seafood",
    "Singaporean",
    "Slovakian",
    "Somali",
    "Soul Food",
    "Soup",
    "Southern",
    "Spanish",
    "Sri Lankan",
    "Steakhouses",
    "Supper Clubs",
    "Sushi Bars",
    "Syrian",
    "Taiwanese",
    "Tapas Bars",
    "Tapas/Small Plates",
    "Tex-Mex",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Uzbek",
    "Vegan",
    "Vegetarian",
    "Vietnamese",
    "Waffles",
    "Wraps"
]